"""add series to posts

Revision ID: 51cafb80733f
Revises: e33a24b1fedd
Create Date: 2026-07-17 04:45:45.838615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cafb80733f'
down_revision: Union[str, None] = 'e33a24b1fedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('series', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_posts_series'), 'posts', ['series'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_series'), table_name='posts')
    op.drop_column('posts', 'series')
    # ### end Alembic commands ###
