"""add email_verified to users

Revision ID: 5284e000bf4e
Revises: 1336504cc438
Create Date: 2026-06-25 17:14:30.881335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5284e000bf4e'
down_revision: Union[str, None] = '1336504cc438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 새 칸은 기본 false로 추가 (앞으로 가입하는 계정은 미인증으로 시작)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    # 백필: 이 기능 도입 전에 이미 있던 계정들은 인증된 것으로 처리 (로그인 잠기지 않게)
    op.execute("UPDATE users SET email_verified = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
