"""add status_checks

Revision ID: 62118f8854d4
Revises: f02bc00a3b57
Create Date: 2026-06-22 12:42:52.151053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62118f8854d4'
down_revision: Union[str, None] = 'f02bc00a3b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('backend_ok', sa.Boolean(), nullable=False),
    sa.Column('database_ok', sa.Boolean(), nullable=False),
    sa.Column('mail_ok', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_checks_checked_at'), 'status_checks', ['checked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_checks_checked_at'), table_name='status_checks')
    op.drop_table('status_checks')
    # ### end Alembic commands ###
