"""add gin index on posts.tags

Revision ID: 77d1e046eda7
Revises: f82f1680515d
Create Date: 2026-07-11 22:45:52.363023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d1e046eda7'
down_revision: Union[str, None] = 'f82f1680515d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_tags', 'posts', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_tags', table_name='posts', postgresql_using='gin')
    # ### end Alembic commands ###
