"""add notify to author_subscriptions

Revision ID: 814d837c28a3
Revises: 51cafb80733f
Create Date: 2026-07-18 06:33:49.237647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814d837c28a3'
down_revision: Union[str, None] = '51cafb80733f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_subscriptions', sa.Column('notify', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_subscriptions', 'notify')
    # ### end Alembic commands ###
