"""add approved to author_subscriptions

Revision ID: d29ba157b9a6
Revises: 814d837c28a3
Create Date: 2026-07-18 06:58:22.946997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29ba157b9a6'
down_revision: Union[str, None] = '814d837c28a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('author_subscriptions', sa.Column('approved', sa.Boolean(), server_default='false', nullable=False))
    # 이 기능 도입 전의 기존 구독은 '이미 활성'이었으므로 승인됨으로 백필(접근 잃지 않게).
    # 이후 새로 생기는 구독만 기본 false(승인 대기)가 된다.
    op.execute("UPDATE author_subscriptions SET approved = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_subscriptions', 'approved')
    # ### end Alembic commands ###
