"""add owner_id and visibility to posts

Revision ID: d6c9c2009ad6
Revises: 86ed6449b339
Create Date: 2026-06-21 19:27:27.212750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c9c2009ad6'
down_revision: Union[str, None] = '86ed6449b339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('visibility', sa.String(length=10), server_default='public', nullable=False))
    op.create_index(op.f('ix_posts_owner_id'), 'posts', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_owner_id'), table_name='posts')
    op.drop_column('posts', 'visibility')
    op.drop_column('posts', 'owner_id')
    # ### end Alembic commands ###
