"""create author_subscriptions

Revision ID: f02bc00a3b57
Revises: d6c9c2009ad6
Create Date: 2026-06-21 20:59:11.051868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02bc00a3b57'
down_revision: Union[str, None] = 'd6c9c2009ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'author_id')
    )
    op.create_index(op.f('ix_author_subscriptions_author_id'), 'author_subscriptions', ['author_id'], unique=False)
    op.create_index(op.f('ix_author_subscriptions_subscriber_id'), 'author_subscriptions', ['subscriber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_subscriptions_subscriber_id'), table_name='author_subscriptions')
    op.drop_index(op.f('ix_author_subscriptions_author_id'), table_name='author_subscriptions')
    op.drop_table('author_subscriptions')
    # ### end Alembic commands ###
