"""add pro_until to users

Revision ID: fd4126c0deb5
Revises: 2329d39d8bb6
Create Date: 2026-07-15 05:44:46.816816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4126c0deb5'
down_revision: Union[str, None] = '2329d39d8bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pro_until')
    # ### end Alembic commands ###
